# Generated by Django 6.0.5 on 2026-05-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0002_alter_owners_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
