# Generated by Django 4.2 on 2026-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0004_remove_phone_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmenttenantbeds',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='commercialtenantbeds',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='tenantbeds',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
