# Generated by Django 6.0.5 on 2026-05-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0005_apartmenttenantbeds_id_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmenttenantbeds',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='commercialtenantbeds',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='tenantbeds',
            name='id_proof',
        ),
    ]
