# Generated by Django 6.0.5 on 2026-05-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0006_remove_apartmenttenantbeds_id_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmenttenantbeds',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='apartmenttenantbeds',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commercialtenantbeds',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='commercialtenantbeds',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantbeds',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='tenantbeds',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
