# Generated by Django 6.0.5 on 2026-05-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0008_remove_apartmenttenantbeds_id_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenent',
            name='aadhar_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenent',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_proofs/'),
        ),
        migrations.AddField(
            model_name='tenent',
            name='is_vacant',
            field=models.BooleanField(default=True),
        ),
    ]
