# Generated by Django 6.0.5 on 2026-05-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0009_tenent_aadhar_id_tenent_aadhar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed'), ('allotted', 'Allotted')], default='pending', max_length=20),
        ),
    ]
