# Generated by Django 6.0.5 on 2026-05-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0010_alter_joinrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenent',
            name='aadhar_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_proofs/'),
        ),
        migrations.AddField(
            model_name='tenent',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='tenent',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
    ]
