# Generated by Django 6.0.5 on 2026-06-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0011_tenent_aadhar_back_image_tenent_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('floor_type', models.CharField(choices=[('room_based', 'Room Based'), ('unit_based', 'Unit Based')], max_length=20)),
            ],
            options={
                'ordering': ['floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(choices=[('room', 'Room'), ('unit', 'Unit')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_number', models.PositiveIntegerField(blank=True, null=True)),
                ('sharing', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_number', models.PositiveIntegerField(blank=True, null=True)),
                ('bhk', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='HAC.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('property_type', models.CharField(choices=[('hostel', 'Hostel'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('facilities', models.JSONField(blank=True, null=True)),
                ('gallery_images', models.JSONField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='property_covers/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='HAC.owners')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='HAC.property'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('property', 'floor_number')},
        ),
    ]
