# Generated by Django 6.0.5 on 2026-06-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0012_floor_accommodation_property_floor_property_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='floor',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
